name: Build and publish artefacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl
      - name: Install libs
        run: |
          sudo apt-get install -y libssl-dev musl
      - name: Build
        run: cargo build --release --target=x86_64-unknown-linux-musl
      - name: Upload artefacts
        uses: actions/upload-artifact@v1
        with:
          name: artefacts
          path: target/x86_64-unknown-linux-musl/release/syncshopify2